#!/usr/bin/env bash
set -euo pipefail
DEBUG=false
entries_dir="/Users/gavin/.crusoe/entries"


usage() {
  cat >&2 <<'USAGE'
Crusoe usage:
# Open today's journal entry in editor
crusoe
USAGE
}


main() {
  echo 'Main'
  local command="${1:-journal}"
  case "$command" in
    journal)
      shift || true
      crusoe::journal "$@"
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown sub-command $1" >&2
      usage
      return 2
      ;;
  esac
};

help(){
  usage
}
crusoe::journal(){
  debug "Crusoe journal"

  local entry_date=""
  local entry_file_path=""
  while [[  $# -gt 0 ]]; do
    case "$1" in
      --debug)
        DEBUG=true
        shift
        ;;
      --today)
        entry_date=$(date +%F)
        shift
        ;;
      --date=*)
        entry_date="${1#--date=}"
        entry_date=$(gdate --date "$entry_date" +%F)
        shift
        ;;
      *)
        echo "Unrecogised option $1"
        shift
        return 2
        ;;
    esac
  done
  entry_date="${entry_date:-$(date +%F)}"
  debug "Writing entry for date $entry_date"

  entry_file_path="$(gdate --date "$entry_date" +'%Y/%m')/$entry_date.md"


  entry_file_path="$entries_dir/$entry_file_path"


  if [ -f "$entry_file_path" ]; then
    debug "File exists $entry_file_path"
  else
    debug "File does not exists $entry_file_path"
    mkdir -p "$(dirname "$entry_file_path")"
    touch "$entry_file_path"
    debug "Created file $entry_file_path"
  fi
  debug "${EDITOR:-nano}" "$entry_file_path"
  "$EDITOR" "$entry_file_path"
  crusoe::git::commit_changes "$entry_file_path", "$entry_date"
}

crusoe::git::commit_changes() {
  local entry_file_path=$1
  local entry_date=$2

  debug "Git dir: $entries_dir"
  git -C $entries_dir add "$entry_file_path"
  git -C $entries_dir commit -m "Update journal for $entry_date"
  git -C $entries_dir push
}
debug(){
  if [[ "$DEBUG" == true ]]; then
    printf '[Crusoe][Debug]: %s\n' "$*" >&2
  fi
}
main "$@";